version: "3.7"
services:
    app:
        build:
            args:
                user: www
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel-image
        container_name: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini

    db:
        image: mysql:5.7
        container_name: laravel-db
        restart: unless-stopped
        ports:
            - "33061:3306"
        environment:
            MYSQL_DATABASE: "laravel-api"
            MYSQL_ROOT_PASSWORD: "secret"
            MYSQL_PASSWORD: "secret1231"
            MYSQL_USER: "user"
        volumes:
            - ./mysql/my.cnf:/etc/mysql/my.cnf
            - ./mysql/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/

    nginx:
        image: nginx:alpine
        container_name: laravel-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: laravel-phpmyadmin
        ports:
            - "8080:80"
